name       : grpc
version    : 1.41.1
release    : 1
source     :
    - https://github.com/grpc/grpc/archive/refs/tags/v1.41.1.tar.gz : 12a4a6f8c06b96e38f8576ded76d0b79bce13efd7560ed22134c2f433bc496ad
    - https://github.com/google/googletest/archive/release-1.10.0/googletest-release-1.10.0.tar.gz : 9dc9157a9a1551ec7a7e43daea9a694a0bb5fb8bec81235d8a1e6ef64c716dcb
homepage   : https://grpc.io/
license    : Apache-2.0
component  : programming.library
summary    : An RPC library and framework
description: |
    gRPC is a modern, open source, high-performance remote procedure call (RPC) framework that can run anywhere. gRPC enables client and server applications to communicate transparently, and simplifies the building of connected systems.
clang      : yes
builddeps  :
    - pkgconfig(absl_hash)
    - pkgconfig(benchmark)
    - pkgconfig(libcares)
    - pkgconfig(protobuf)
    - pkgconfig(re2)
    - re2c
rundeps    :
    - devel :
        - c-ares-devel
        - protobuf-devel
        - re2-devel
environment: |
    export CXXFLAGS="$CXXFLAGS -DNDEBUG"
setup      : |
    %patch -p1 < $pkgfiles/grpc-assert.patch

    rm -rf third_party/{abseil-cpp,googletest,benchmark}
    mkdir third_party/{abseil-cpp,googletest,benchmark}
    tar xf $sources/googletest-* --strip-components=1 -C third_party/googletest

    %cmake_ninja \
        -DCMAKE_CXX_STANDARD=17 \
        -DCMAKE_SKIP_INSTALL_RPATH=ON \
        -DBUILD_SHARED_LIBS=ON \
        -DgRPC_INSTALL=ON \
        -DgRPC_BUILD_CODEGEN=ON \
        -DgRPC_BUILD_TESTS=ON \
        -DgRPC_BUILD_CSHARP_EXT=OFF \
        -DgRPC_BACKWARDS_COMPATIBILITY_MODE=OFF \
        -DgRPC_USE_PROTO_LITE=OFF \
        -DgRPC_BUILD_GRPC_CPP_PLUGIN=ON \
        -DgRPC_BUILD_GRPC_CSHARP_PLUGIN=OFF \
        -DgRPC_BUILD_GRPC_NODE_PLUGIN=OFF \
        -DgRPC_BUILD_GRPC_OBJECTIVE_C_PLUGIN=OFF \
        -DgRPC_BUILD_GRPC_PHP_PLUGIN=OFF \
        -DgRPC_BUILD_GRPC_PYTHON_PLUGIN=ON \
        -DgRPC_BUILD_GRPC_RUBY_PLUGIN=OFF \
        -DgRPC_ABSL_PROVIDER=package \
        -DgRPC_BENCHMARK_PROVIDER=package \
        -DgRPC_CARES_PROVIDER=package \
        -DgRPC_PROTOBUF_PROVIDER=package \
        -DgRPC_PROTOBUF_PACKAGE_TYPE=MODULE \
        -DgRPC_RE2_PROVIDER=package \
        -DgRPC_SSL_PROVIDER=package \
        -DgRPC_ZLIB_PROVIDER=package
build      : |
    %ninja_build
install    : |
    %ninja_install
